'use strict';

describe('Service: ApiService', function () {
  beforeEach(module('app'));
  beforeEach(module('ngMock'));
  //Add templates module to avoid http requests for html files
  //This is generated by html2js preprocessor
  beforeEach(module('templates'));

  var ApiSrv, httpBackend, q, deferred, rootScope;

  beforeEach(inject(function (_ApiService_, _$httpBackend_, _$q_, $rootScope) {
    ApiSrv = _ApiService_;
    httpBackend = _$httpBackend_;
    q = _$q_;
    deferred = _$q_.defer();
    rootScope = $rootScope;
  }));

  it('should exist', function () {
    expect(!!ApiSrv).toBe(true);
  });

  describe('API Calls work completely', function () {
    it('should GET /api/registration/<guid>', function () {
        httpBackend.expectGET('/api/registration/aa7a77a7a').respond(200);
        httpBackend.whenGET(/assets\/locale\/.*/).respond({});
        ApiSrv.getGuid('aa7a77a7a');
        httpBackend.flush();
    });

    it('should PUT /api/registration/<guid>?action=<action>', function () {
        httpBackend.expectPUT('/api/registration/aa7a77a7a?action=save').respond(201);
        httpBackend.whenGET(/assets\/locale\/.*/).respond({});
        ApiSrv.createRegistration('aa7a77a7a', 'save', {"pin": "1234"});
        httpBackend.flush();
    });
  });

  describe('API Calls do not work completely', function () {
    it('should GET /api/registration/<guid>', function () {
      var response;
      deferred.promise.catch(function(data) {
        response = data;
      });
      deferred.reject('Error');
      httpBackend.expectGET('/api/registration/aa7a77a7a').respond(404);
      httpBackend.whenGET(/assets\/locale\/.*/).respond({});
      ApiSrv.getGuid('aa7a77a7a');
      rootScope.$apply();

      expect(response).toBe('Error');
      //httpBackend.flush();
    });

    it('should PUT /api/registration/<guid>?action=<action>', function () {
      var response;
      deferred.promise.catch(function(data) {
        response = data;
      });
      deferred.reject('Error');

      httpBackend.expectPUT('/api/registration/aa7a77a7a?action=save').respond(404);
      httpBackend.whenGET(/assets\/locale\/.*/).respond({});
      ApiSrv.createRegistration('aa7a77a7a', 'save', {"pin": "1234"});
      rootScope.$apply();

      expect(response).toBe('Error');
    });
  });
  
});
