SET IDENTITY_INSERT [dbo].[KpiRegions] ON
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (1, NULL, N'Children''s Services', 1, 1)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (2, 1, N'North East', 2, 5003)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (3, 1, N'North West', 2, 5004)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (4, 1, N'South East', 2, 5005)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (5, 1, N'South West', 2, 5006)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (6, 3, N'GM East', 3, 5009)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (7, 3, N'GM West', 3, 5010)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (8, 3, N'Warrington & Halton', 3, 5011)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (9, 4, N'West Midlands', 3, 5012)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (10, 2, N'North East', 3, 5007)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (11, 2, N'Yorkshire', 3, 5008)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (12, 4, N'East Midlands', 3, 5013)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (13, 4, N'Essex & London', 3, 5015)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (14, 5, N'Hereford & Worcester', 3, 5018)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (15, 5, N'South West Mike', 3, 5016)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (16, 4, N'Wisbech', 3, 5014)
INSERT [dbo].[KpiRegions] ([KpiRegionID], [ParentID], [KpiRegionName], [KpiRegionTypeID], [RegionManagerID]) VALUES (17, 5, N'South West Katie', 3, 5017)
SET IDENTITY_INSERT [dbo].[KpiRegions] OFF
