INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1001, N'Alexandra Road', 6, NULL, 5001)INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1002, N'Cronkeyshaw Road', 6, NULL, 5040)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1003, N'East Road', 6, NULL, 5041)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1004, N'Fox Street', 6, NULL, 5042)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1005, N'Fraser Street', 6, NULL, 5043)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1006, N'Further Heights', 6, NULL, 5040)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1007, N'Gloucester', 6, NULL, 5044)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1008, N'Linden Road', 6, NULL, 5045)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1009, N'Pilsworth', 6, NULL, 5040)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1010, N'Regent', 6, NULL, 5044)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1011, N'The Haven', 6, NULL, 5045)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1012, N'Weston Avenue', 6, NULL, 5042)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1013, N'Windsor Road', 6, NULL, 5047)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1014, N'Chesham House', 6, NULL, 5048)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1015, N'Beech Mount', 7, NULL, 5050)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1016, N'Birch House Care 1 Daisybank', 7, NULL, 5051)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1017, N'Birch House Care 2 Bluebell', 7, NULL, 5051)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1018, N'Booth', 7, NULL, 5052)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1019, N'Braemar House', 7, NULL, 5053)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1020, N'Brook House', 7, NULL, 5053)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1021, N'Cleveland Road', 7, NULL, 5053)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1022, N'Halsbury', 7, NULL, 5054)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1023, N'Holden Fold', 7, NULL, 5049)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1024, N'Lower Park House', 7, NULL, 5055)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1025, N'Lyndene Road', 7, NULL, 5056)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1026, N'Meadow Road', 7, NULL, 5057)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1027, N'Parkhill', 7, NULL, 5049)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1028, N'Poolbank', 7, NULL, 5057)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1029, N'Queens Park Road', 7, NULL, 5057)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1030, N'Rooley Moor Road', 7, NULL, 5052)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1031, N'Summit Street', 7, NULL, 5052)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1032, N'Abbey Close', 8, NULL, 5058)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1033, N'Fletcher Street', 8, NULL, 5058)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1034, N'Peelhouse - 110', 8, NULL, 5058)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1035, N'Fitzwalter Road', 8, NULL, 5061)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1036, N'Kingsway North', 8, NULL, 5061)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1037, N'The Gables', 8, NULL, 5061)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1038, N'Halton View', 8, NULL, 5062)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1039, N'Greenway', 8, NULL, 5062)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1040, N'Liverpool Road', 8, NULL, 5062)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1041, N'Lower House Lane', 8, NULL, 5063)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1042, N'Lunts Heath', 8, NULL, 5063)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1043, N'Peelhouse - 62', 8, NULL, 5064)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1044, N'Willoughby', 8, NULL, 5064)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1045, N'Rydal Avenue', 8, NULL, 5059)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1046, N'South Parade', 8, NULL, 5059)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1047, N'Cheshire Flats', 8, NULL, 5059)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1048, N'Eland House', 8, NULL, 5060)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1049, N'Beech Way', 9, NULL, 5065)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1050, N'Brooklands Parade', 9, NULL, 5066)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1051, N'Cedar Drive', 9, NULL, 5067)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1052, N'Cranhill', 9, NULL, 5068)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1053, N'Fensgrove', 9, NULL, 5069)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1054, N'Grange House', 9, NULL, 5070)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1055, N'Greenridge Road', 9, NULL, 5071)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1056, N'Hay Park', 9, NULL, 5072)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1057, N'Herbert Road', 9, NULL, 5072)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1058, N'Mayfield House', 9, NULL, 5073)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1059, N'Merridale House', 9, NULL, 5074)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1060, N'Middle Leaford', 9, NULL, 5075)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1061, N'Southbourne Avenue', 9, NULL, 5076)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1062, N'Stafford Road', 9, NULL, 5077)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1063, N'The Wergs', 9, NULL, 5078)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1064, N'Bowburn', 10, NULL, 5019)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1065, N'Bruce Avenue', 10, NULL, 5020)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1066, N'Church Rise', 10, NULL, 5021)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1067, N'Kennedy House', 10, NULL, 5020)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1068, N'Linden House', 10, NULL, 5022)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1069, N'Meadow Rise', 10, NULL, 5023)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1071, N'Prince Bishop', 10, NULL, 5026)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1072, N'Stainton', 10, NULL, 5027)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1073, N'Moore Park (Caxton)', 10, NULL, 5024)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1074, N'Algerdene', 11, NULL, 5028)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1075, N'Avenue Victoria', 11, NULL, 5029)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1076, N'College Street', 11, NULL, 5030)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1077, N'Inglemire Lane', 11, NULL, 5031)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1078, N'Inglemire Cottage', 11, NULL, 5031)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1079, N'Kirkstall House', 11, NULL, 5032)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1080, N'Kirklees Flats', 11, NULL, 5030)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1081, N'Lister View', 11, NULL, 5033)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1082, N'Mount View', 11, NULL, 5034)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1083, N'New Gables', 11, NULL, 5035)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1084, N'Oastler House', 11, NULL, 5036)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1085, N'Park Avenue', 11, NULL, 5037)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1086, N'Park Avenue Flat', 11, NULL, 5037)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1087, N'Woodborough House', 11, NULL, 5038)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1088, N'Abbeyfield', 12, NULL, 5079)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1089, N'Abington Grove', 12, NULL, 5080)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1090, N'Castle Rock', 12, NULL, 5081)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1091, N'Forest Field House', 12, NULL, 5082)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1092, N'Forestfield Flats', 12, NULL, 5082)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1093, N'Main Street', 16, NULL, 5083)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1094, N'Murrow House', 16, NULL, 5084)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1095, N'Nene House Flat', 12, NULL, 5085)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1096, N'Nene House', 12, NULL, 5085)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1098, N'Queens Park Parade Flats', 12, NULL, 5087)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1099, N'Queens Park Parade', 12, NULL, 5086)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1100, N'Queens Road', 16, NULL, 5088)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1101, N'Rose House', 16, NULL, 5089)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1102, N'Sunnyside', 16, NULL, 5090)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1103, N'Conifers', 13, NULL, 5091)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1104, N'Goodfellows', 13, NULL, 5093)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1105, N'Nutwood Cottage', 13, NULL, 5094)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1106, N'Pear Tree', 13, NULL, 5126)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1107, N'Tudor Cottage', 13, NULL, 5096)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1108, N'Whitewebbs', 13, NULL, 5098)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1109, N'Finching Field', 13, NULL, 5095)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1110, N'Walnut Tree Lodge', 13, NULL, 5083)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1111, N'Arrowbridge', 14, NULL, 5114)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1112, N'Broomhill Cottage', 14, NULL, 5115)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1113, N'Burfa House', 14, NULL, 5116)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1114, N'Chlamys House', 14, NULL, 5117)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1115, N'Gilwern', 14, NULL, 5118)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1116, N'Hanter House', 14, NULL, 5119)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1117, N'Mid Meadows', 14, NULL, 5120)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1118, N'Perrymill', 14, NULL, 5121)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1119, N'Rosebank Cottage', 14, NULL, 5122)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1121, N'Woodfield Oaks', 14, NULL, 5124)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1122, N'Blaxton Farm', 15, NULL, 5099)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1123, N'Broadfield', 17, NULL, 5100)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1124, N'Harvest Barn', 15, NULL, 5101)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1125, N'Hillesdon Road', 15, NULL, 5102)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1126, N'Hillesdon Road Flat', 15, NULL, 5101)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1127, N'Hillesdon Road Cottage', 15, NULL, 5101)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1128, N'Horsham Farm', 15, NULL, 5103)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1129, N'Hoxton Road', 15, NULL, 5102)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1130, N'Lapinsfield', 17, NULL, 5127)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1131, N'Mill Park House', 15, NULL, 5105)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1132, N'Prospect House', 15, NULL, 5107)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1133, N'Palm Lodge', 15, NULL, 5099)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1134, N'Orchid Vale', 15, NULL, 5106)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1135, N'Sandy Bay', 17, NULL, 5109)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1136, N'Shaptor Farm', 17, NULL, 5110)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1137, N'Sunrise House', 15, NULL, 5107)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1138, N'Russets Court', 17, NULL, 5108)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1140, N'Woodmere', 15, NULL, 5106)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1141, N'Writh Lodge', 17, NULL, 5112)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1142, N'Wyre Close', 15, NULL, 5113)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1143, N'Park View (Saltwell)', 10, NULL, 5025)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1144, N'The Marshes', 14, NULL, 5123)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1145, N'Pelham Road', 6, NULL, 5044)
INSERT [dbo].[tblSites] ([SiteID], [SiteName], [KpiRegionID], [Type], [SiteManagerID]) VALUES (1146, N'Fensgrove Flats', 9, NULL, 5069)
